apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: dbcluster01
spec:
  secretName: mysql-secret
  tlsUseSelfSigned: true
  instances: 3
  version: 9.4.0
  imagePullSecrets:
    - name: oracle-registry-secret
  router:
    instances: 3
  datadirVolumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 5Gi